import os
import time
from git import Repo, InvalidGitRepositoryError, GitCommandError
from github import Github
from langchain_core.tools import tool

# Workspace injected from main.py or test script
WORKSPACE_PATH = ""

DEFAULT_GITIGNORE = """
node_modules/
.env
__pycache__/
*.pyc
dist/
build/
.DS_Store
"""


def _ensure_gitignore(repo: Repo):
    path = os.path.join(WORKSPACE_PATH, ".gitignore")
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(DEFAULT_GITIGNORE.strip())
        repo.git.add(".gitignore")


def _safe_pull(repo: Repo, branch: str):
    try:
        repo.git.pull("origin", branch, "--rebase")
    except Exception:
        pass  # ignore if first push


def _push_with_retry(origin, branch: str, retries=3):
    for i in range(retries):
        result = origin.push(refspec=f"{branch}:{branch}", set_upstream=True)

        for res in result:
            if res.flags & res.ERROR:
                print(f"❌ Push error: {res.summary}")
                time.sleep(2)
                break
        else:
            print("🚀 Push successful")
            return True

    raise Exception("Push failed after retries")


@tool
def deploy_to_github(branch: str, commit_message: str, create_pr: bool) -> str:
    """
    Deploy workspace to GitHub (repo-aware, safe, production-ready)

    Args:
        branch: Branch name (e.g., "feature/login")
        commit_message: Commit message
        create_pr: Whether to create PR

    Returns:
        Status message
    """

    try:
        # 🔐 ENV CONFIG
        repo_url = os.getenv("GITHUB_REPO_URL")
        repo_name = os.getenv("GITHUB_REPO_NAME")
        token = os.getenv("GITHUB_TOKEN")

        if not repo_url or not repo_name or not token:
            return "ERROR: Missing GitHub environment variables"

        if not WORKSPACE_PATH or not os.path.exists(WORKSPACE_PATH):
            return "ERROR: Invalid WORKSPACE_PATH"

        # 1️⃣ INIT / LOAD REPO
        try:
            repo = Repo(WORKSPACE_PATH)
        except InvalidGitRepositoryError:
            repo = Repo.init(WORKSPACE_PATH)
            print("✅ Initialized git repo")

        # 2️⃣ SETUP REMOTE
        try:
            origin = repo.remote(name="origin")
        except ValueError:
            origin = repo.create_remote("origin", repo_url)
            print("✅ Added remote origin")

        # 3️⃣ CHECKOUT BRANCH
        try:
            repo.git.checkout(branch)
        except GitCommandError:
            repo.git.checkout("-b", branch)
            print(f"✅ Created branch: {branch}")

        # 4️⃣ ENSURE GITIGNORE
        _ensure_gitignore(repo)

        # 5️⃣ PULL LATEST (repo-aware)
        _safe_pull(repo, branch)

        # 6️⃣ ADD + COMMIT
        repo.git.add(all=True)

        if not repo.is_dirty(untracked_files=True):
            return "No changes to commit"

        repo.index.commit(commit_message)
        print(f"✅ Commit: {commit_message}")

        # 7️⃣ PUSH
        _push_with_retry(origin, branch)
        print("🚀 Push successful")

        # 8️⃣ CREATE PR (optional)
        if create_pr:
            g = Github(token)
            gh_repo = g.get_repo(repo_name)

            pr = gh_repo.create_pull(
                title=commit_message,
                body="Auto-generated by agent",
                head=branch,
                base="main"
            )

            return f"Success: PR created → {pr.html_url}"

        return f"Success: Changes pushed to '{branch}'"

    except Exception as e:
        return f"ERROR: {str(e)}"